---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: netbox-secret
    creationPolicy: Owner
    template:
      data:
        postgresql-password: "{{ .postgres_password }}"
        cache-password: ""
        tasks-password: ""
  data:
    - secretKey: postgres_password
      remoteRef:
        key: netbox
        property: postgresql_password
