---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: forgejo
spec:
  kanidmRef:
    name: kanidm
    namespace: security
  displayname: "forgejo"
  origin: "https://git.lucadev.de/"
  image:
    url: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons@main/svg/forgejo.svg"
  redirectUrl:
    - "https://git.lucadev.de/user/oauth2/IDM/callback"
  scopeMap:
    - group: service_users
      scopes: [email, groups, openid, profile, ssh_publickeys]
  preferShortUsername: true
  disableConsentPrompt: true
  secretKeyAliases:
    clientId:
      - key
    clientSecret:
      - secret
