{
 "title": "SMART",
 "description": "Extended smartmon Dashboard for disk SMART data",
 "tags": [
  "prometheus",
  "node_exporter",
  "smartmon"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(smartctl_device,instance)"
    }
   },
   {
    "name": "disk",
    "query": {
     "query": "label_values(smartctl_device,device)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "smartctl_device_smart_status", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "Disks",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "smartctl_device_smart_status{instance=~\"$instance\"} + on(device) group_left(firmware_version, form_factor, model_name, protocol, serial_number) ( smartctl_device )",
     "legendFormat": "__auto"
    },
    {
     "expr": "smartctl_device_power_on_seconds{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "smartctl_device_available_spare{instance=~\"$instance\"}",
     "legendFormat": "Spare"
    }
   ]
  },
  {
   "title": "Disk Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "smartctl_device_temperature{instance=~\"$instance\",device=~\"$disk\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Pending and Reallocated Sectors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "sectors" } },
   "targets": [
    {
     "expr": "smartctl_device_attribute{instance=~\"$instance\",device=~\"$disk\",attribute_id=\"5\", attribute_value_type=\"raw\"}",
     "legendFormat": "Reallocated {{device}}"
    },
    {
     "expr": "smartctl_device_attribute{instance=~\"$instance\",device=~\"$disk\",attribute_id=\"197\", attribute_value_type=\"raw\"}",
     "legendFormat": "Pending {{device}}"
    }
   ]
  },
  {
   "title": "Raw Error Read Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "smartctl_device_media_errors{device=~\"$disk\", instance=~\"$instance\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Total Data Written on SSDs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "smartctl_device_bytes_written{device=~\"nvme.*\", device=~\"$disk\", instance=~\"$instance\"}",
     "legendFormat": "{{device}} written"
    },
    {
     "expr": "smartctl_device_bytes_read{device=~\"nvme.*\", device=~\"$disk\", instance=~\"$instance\"}",
     "legendFormat": "{{device}} read"
    }
   ]
  },
  {
   "title": "Attrs",
   "type": "table",
   "gridPos": { "h": 16, "w": 13, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "smartctl_device_attribute{instance=~\"$instance\", device=~\"$disk\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}