{
 "title": "OpenDTU",
 "description": "Dashboard for OpenDTU",
 "tags": [ "solar" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(opendtu_build,instance)"
    }
   },
   {
    "name": "serial",
    "query": {
     "query": "label_values(opendtu_last_update,serial)"
    }
   },
   {
    "name": "channel",
    "query": {
     "query": "label_values(opendtu_PanelInfo,channel)"
    }
   },
   { "name": "bar_chart_interval", "label": "Bar Chart Interval", "query": "15m,30m,1h,2h" },
   { "name": "bar_chart_duration", "label": "Bar Chart Duration", "query": "7d,14d,30d,60d,90d" },
   { "name": "cent", "label": "Cent / kWh", "query": "30" },
   {
    "name": "solar_cost",
    "label": "Costs of installed Solar System",
    "query": "224.5"
   }
  ]
 },
 "panels": [
  {
   "title": "OpenDTU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "OpenDTU Build",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "opendtu_build{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Platform Arch",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "opendtu_platform{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Heap",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "opendtu_free_heap_size{instance=\"$instance\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "opendtu_heap_size{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "WiFi RSSI",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 14, "x": 10, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "expr": "wifi_rssi{instance=\"$instance\"}",
       "legendFormat": "rssi"
      }
     ]
    },
    {
     "title": "OpenDTU ID",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "opendtu_build{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "OpenDTU Version",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "opendtu_build{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Platform MAC",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "opendtu_platform{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "OpenDTU Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "opendtu_uptime{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "WiFi BSSID",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 6, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wifi_station{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Last Update",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "targets": [
      { "expression": "$uptime-$last_update", "type": "math" }
     ]
    }
   ]
  },
  { "title": "Inverter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Last Update",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$uptime-$last_update", "type": "math" }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opendtu_Temperature{instance=\"$instance\", serial=~\"$serial\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Production (Today - AC)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opendtu_YieldDay{instance=\"$instance\", serial=~\"$serial\", type=\"AC\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Production (Total - AC)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opendtu_YieldTotal{instance=\"$instance\", serial=~\"$serial\", type=\"AC\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opendtu_Power{instance=\"$instance\", serial=~\"$serial\", type=\"AC\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Highest Power Peak (AC)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(opendtu_Power{instance=\"$instance\", serial=~\"$serial\", type=\"AC\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Highest Power Peak (DC)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(opendtu_Power{instance=\"$instance\", serial=~\"$serial\", type=\"DC\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opendtu_last_update{instance=\"$instance\", serial=~\"$serial\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "opendtu_Voltage{instance=\"$instance\", serial=~\"$serial\", type=\"AC\"}",
     "legendFormat": "AC"
    },
    {
     "expr": "opendtu_Voltage{instance=\"$instance\", serial=~\"$serial\", type=\"DC\"}",
     "legendFormat": "DC {{channel}}"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "opendtu_Current{instance=\"$instance\", serial=~\"$serial\", type=\"AC\"}",
     "legendFormat": "AC Current"
    },
    {
     "expr": "opendtu_Current{instance=\"$instance\", serial=~\"$serial\", type=\"DC\"}",
     "legendFormat": "DC {{channel}} Current"
    }
   ]
  },
  {
   "title": "Power Factor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "opendtu_PowerFactor{instance=\"$instance\", serial=~\"$serial\"}",
     "legendFormat": "Power Factor"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "opendtu_Power{instance=\"$instance\", serial=~\"$serial\", type=\"AC\"}",
     "legendFormat": "Total AC Power"
    },
    {
     "expr": "opendtu_PowerDC{instance=\"$instance\", serial=~\"$serial\"}",
     "legendFormat": "Total DC Power"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "opendtu_Temperature{instance=\"$instance\", serial=~\"$serial\"}",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "title": "Reactive Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "voltampreact" } },
   "targets": [
    {
     "expr": "opendtu_ReactivePower{instance=\"$instance\", serial=~\"$serial\"}",
     "legendFormat": "Reactive Power"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "opendtu_Frequency{instance=\"$instance\", serial=~\"$serial\"}",
     "legendFormat": "Frequency"
    }
   ]
  },
  {
   "title": "Efficiency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "opendtu_Efficiency{instance=\"$instance\", serial=~\"$serial\"}",
     "legendFormat": "Efficiency"
    }
   ]
  },
  {
   "title": "Per Day (Last $bar_chart_duration)",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "max_over_time(opendtu_YieldDay{instance=\"$instance\", serial=~\"$serial\", type=\"AC\"}[1d])",
     "legendFormat": "Energy"
    }
   ]
  },
  {
   "title": "Avg Power per Hour (Last 24h)",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg_over_time(opendtu_Power{instance=\"$instance\", serial=~\"$serial\", type=\"AC\"}[$bar_chart_interval])",
     "legendFormat": "Energy"
    }
   ]
  },
  {
   "title": "Power Loss in W",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "opendtu_Power{instance=\"$instance\", serial=~\"$serial\", type=\"AC\"} / opendtu_Efficiency{instance=\"$instance\", serial=~\"$serial\"} * 100 - opendtu_Power{instance=\"$instance\", serial=~\"$serial\", type=\"AC\"}",
     "legendFormat": "Loss"
    }
   ]
  },
  {
   "title": "Yield (€) ($cent cent)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opendtu_YieldTotal{instance=\"$instance\", serial=~\"$serial\", type=\"AC\"} * $cent / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Yield (avg €/day) ($cent cent, $bar_chart_duration)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max_over_time(opendtu_YieldDay{instance=\"$instance\", serial=~\"$serial\", type=\"AC\"}[1d]) / 1000 * $cent / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Days until solar (using avg €/day) ($cent cent, $bar_chart_duration)",
   "type": "stat",
   "description": "Total cost: $solar_cost€",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max_over_time(opendtu_YieldDay{instance=\"$instance\", serial=~\"$serial\", type=\"AC\"}[1d]) / 1000 * $cent / 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "opendtu_YieldTotal{instance=\"$instance\", serial=~\"$serial\", type=\"AC\"} * $cent / 100",
     "legendFormat": "__auto"
    },
    {
     "expression": "($solar_cost - $total_savings) / $euros_per_day",
     "type": "math"
    }
   ]
  },
  { "title": "Channel $channel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 }, "repeat": "channel" },
  {
   "title": "Panel Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opendtu_PanelInfo{instance=\"$instance\", serial=~\"$serial\", channel=\"$channel\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Max Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opendtu_MaxPower{instance=\"$instance\", serial=~\"$serial\", channel=\"$channel\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Channel $channel",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opendtu_Power{instance=\"$instance\", serial=~\"$serial\", type=\"DC\", channel=\"$channel\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Production Channel $channel (Today)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opendtu_YieldDay{instance=\"$instance\", serial=~\"$serial\", type=\"DC\", channel=\"$channel\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Production Channel $channel (Total)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opendtu_YieldTotal{instance=\"$instance\", serial=~\"$serial\", type=\"DC\", channel=\"$channel\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Irradiation Channel $channel",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opendtu_Irradiation{instance=\"$instance\", serial=~\"$serial\", type=\"DC\", channel=\"$channel\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Channel Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "opendtu_Voltage{instance=\"$instance\", serial=~\"$serial\", channel=\"$channel\", type=\"DC\"}",
     "legendFormat": "Channel {{channel}} DC Voltage"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "opendtu_Current{instance=\"$instance\", serial=~\"$serial\", type=\"DC\", channel=\"$channel\"}",
     "legendFormat": "Channel {{channel}} DC Current"
    }
   ]
  },
  {
   "title": "Irradiation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "opendtu_Irradiation{instance=\"$instance\", serial=~\"$serial\", type=\"DC\", channel=\"$channel\"}",
     "legendFormat": "Channel {{channel}} Irradiation"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "opendtu_Power{instance=\"$instance\", serial=~\"$serial\", channel=\"$channel\", type=\"DC\"}",
     "legendFormat": "Total DC Power"
    },
    {
     "expr": "opendtu_MaxPower{instance=\"$instance\", serial=~\"$serial\", channel=\"$channel\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}