---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: cloudflare
spec:
  kanidmRef:
    name: kanidm
  displayname: "Cloudflare"
  origin: "https://kroeger.cloudflareaccess.com/"
  redirectUrl:
    - "https://kroeger.cloudflareaccess.com/cdn-cgi/access/callback"
  scopeMap:
    - group: idm_all_persons
      scopes: [email, groups, openid, profile]
  disableConsentPrompt: true
