---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: openclouddesktop
spec:
  kanidmRef:
    name: kanidm
    namespace: security
  displayname: "OpenCloudDesktop"
  origin: "http://127.0.0.1/"
  public: true
  redirectUrl:
    - "http://localhost/"
  scopeMap:
    - group: file_users
      scopes: [email, groups, offline_access, openid, profile]
  preferShortUsername: true
