---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kubeexposure-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: kubeexposure-secret
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: KubeExposure
        property: jwt-secret
    - secretKey: encryption-key
      remoteRef:
        key: KubeExposure
        property: encryption-key
    - secretKey: postgres-password
      remoteRef:
        key: KubeExposure
        property: postgres-password
