---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-exposure
  namespace: security
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: kube-exposure
    namespace: security
  values:
    replicaCount: 1
    postgres:
      enabled: false
    externalDatabaseSecretName: kubeexposure-secret
    jwtSecretName: kubeexposure-secret
    encryptionSecretName: kubeexposure-secret
    dragonflySecretName: kubeexposure-secret
    postgresSecretName: kubeexposure-secret
    externalDatabase:
      host: "shared-pg-rw.databases.svc.cluster.local"
      port: 5432
      user: "kubeexposure"
      db: "kubeexposure"
