---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: memos
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: memos-secret
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: memos
        property: OIDC_SECRET
