---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: memos
spec:
  kanidmRef:
    name: kanidm
    namespace: security
  displayname: "Memos"
  origin: "https://notes.home.lucadev.de/"
  redirectUrl:
    - "https://notes.lucadev.de/oidc/callback"
    - "https://notes.lucadev.de/auth/callback"
  scopeMap:
    - group: idm_all_persons
      scopes: [email, openid, profile]
    - group: service_users
      scopes: [email, groups, openid, profile]
  preferShortUsername: true
  disableConsentPrompt: true
