---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: memos
spec:
  kanidmRef:
    name: kanidm
    namespace: security
  displayname: "Memos"
  origin: "https://notes.home.lucadev.de/"
  image:
    url: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons@main/svg/memos.svg"
  redirectUrl:
    - "https://notes.lucadev.de/oidc/callback"
  scopeMap:
    - group: idm_all_persons
      scopes:
        - email
        - openid
        - profile
    - group: service_users
      scopes:
        - email
        - groups
        - openid
        - profile
  preferShortUsername: true
  disableConsentPrompt: true
  secretKeyAliases:
    clientSecret:
      - client-secret
