---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bookboss-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: bookboss
    template:
      data:
        BOOKBOSS__ENCRYPTION_SECRET: "{{ .bookboss_encryption_secret }}"
  data:
    - secretKey: bookboss_encryption_secret
      remoteRef:
        key: Bookboss
        property: encryption_secret
