---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: bookboss
spec:
  kanidmRef:
    name: kanidm
    namespace: security
  displayname: "BookBoss"
  origin: "https://books.lucadev.de/"
  redirectUrl:
    - "https://books.lucadev.de/auth/oidc/callback"
  scopeMap:
    - group: media_users
      scopes: [email, groups, openid, profile]
    - group: admins
      scopes: [email, groups, openid, profile]
  preferShortUsername: true
  disableConsentPrompt: true
