{
 "title": "Fritz!Exporter Dash",
 "description": "Dashboard for FRITZ!Box routers using Prometheus and fritz_exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "serial",
    "query": {
     "query": "label_values(fritz_update_available,serial)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Fritzbox Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_uptime_seconds_total{serial=\"$serial\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "uptime" }
     ]
    }
   ]
  },
  {
   "title": "IP Connection Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_ppp_connection_state{serial=\"$serial\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "constatus" }
     ]
    }
   ]
  },
  {
   "title": "# Known Devices",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_known_devices_count{serial=\"$serial\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Connected WIFI",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fritz_wifi_associations_count{serial=\"$serial\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "fritz_update_available{serial=\"$serial\"} * on(serial) group_right() fritz_uptime_seconds_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_ppp_connection_uptime_seconds_total{serial=\"$serial\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "uptime" }
     ]
    }
   ]
  },
  {
   "title": "DSL Link Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_dsl_status{serial=\"$serial\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "dslstatus" }
     ]
    }
   ]
  },
  {
   "title": "DSL Attenuation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "fritz_dsl_attenuation_dB{serial=\"$serial\"}",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "DSL Noise margin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "fritz_dsl_noise_margin_dB{serial=\"$serial\"}",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "# WIFI Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "fritz_wifi_associations_count{serial=~\"$serial\"}",
     "legendFormat": "{{wifi_name}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "fritz_wan_data_bytes_total{serial=\"$serial\"}",
     "measurement": "fritzbox_value",
     "query": "SELECT cumulative_sum(max(\"value\")) FROM \"fritzbox_value\" WHERE (\"type_instance\" = 'totalbytesreceived') AND $timeFilter GROUP BY time($__interval) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
     ]
    }
   ]
  },
  {
   "title": "Hourly Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "fritz_wan_datarate_bytes{serial=\"$serial\", direction=\"rx\"}",
     "legendFormat": "Download"
    },
    {
     "expr": "fritz_wan_datarate_bytes{serial=\"$serial\", direction=\"tx\"}",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "fritz_wan_data_bytes_total{serial=\"$serial\"}",
     "measurement": "fritzbox_value",
     "query": "SELECT cumulative_sum(non_negative_difference(last(\"value\"))) FROM \"fritzbox_value\" WHERE (\"type_instance\" = 'totalbytessent') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytessent" }
     ]
    }
   ]
  },
  {
   "title": "DSL errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "fritz_dsl_fec_errors_count_total{serial=\"$serial\"}",
     "legendFormat": "FEC Errors"
    },
    {
     "expr": "fritz_dsl_crc_errors_count_total{serial=\"$serial\"}",
     "legendFormat": "CRC Errors"
    }
   ]
  },
  {
   "title": "DSL Connection Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    { "expr": "fritz_dsl_noise_margin_dB", "legendFormat": "Noice Margin {{direction}}" },
    { "expr": "fritz_dsl_attenuation_dB", "legendFormat": "Attenuation {{direction}}" }
   ]
  },
  {
   "title": "Bandwith",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "fritz_wan_max_bitrate_bps{serial=\"$serial\",direction=\"rx\"}",
     "legendFormat": "Download Limit"
    },
    {
     "expr": "fritz_wan_datarate_bytes{serial=\"$serial\", direction=\"rx\"}*8",
     "legendFormat": "Download Usage"
    },
    {
     "expr": "fritz_wan_max_bitrate_bps{serial=\"$serial\",direction=\"tx\"}",
     "legendFormat": "Upload Limit"
    },
    {
     "expr": "fritz_wan_datarate_bytes{serial=\"$serial\", direction=\"tx\"}*8",
     "legendFormat": "Upload Usage"
    }
   ]
  },
  {
   "title": "WIFIs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "fritz_wifi_associations_count", "legendFormat": "__auto" },
    {
     "expr": "fritz_wifi_channel{serial=\"$serial\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}