---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: rustfs-secret
    creationPolicy: Owner
    template:
      data:
        RUSTFS_ACCESS_KEY: "{{ .RUSTFS_ROOT_USER }}"
        RUSTFS_SECRET_KEY: "{{ .RUSTFS_ROOT_PASSWORD }}"
  data:
    - remoteRef:
        key: rustfs
        property: root_user
      secretKey: RUSTFS_ROOT_USER
    - remoteRef:
        key: rustfs
        property: root_password
      secretKey: RUSTFS_ROOT_PASSWORD
