---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bichon-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: bichon
    template:
      data:
        BICHON_ENCRYPT_PASSWORD: "{{ .bichon_encryption_password }}"
  data:
    - secretKey: bichon_encryption_password
      remoteRef:
        key: Bichon
        property: bichon_encryption_password
