---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-secret
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: homepage-secret
    creationPolicy: Owner
    template:
      data:
        HOMEPAGE_OIDC_CLIENT_SECRET: "{{ .homepage_oidc_client_secret }}"
  data:
    - secretKey: homepage_oidc_client_secret
      remoteRef:
        key: 875d4fc0-6bc1-493c-a8bb-b07c00c08ee1
        property: homepage_oidc_secret
