---
apiVersion: kaniop.rs/v1beta1
kind: Kanidm
metadata:
  name: kanidm
  namespace: security
spec:
  domain: idm.lucadev.de
  image: kanidm/server:1.11.1
  replicaGroups:
    - name: default
      replicas: 1
      primaryNode: true
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: ssd-dualreplica
        resources:
          requests:
            storage: 1Gi
  tlsSecretName: idm-lucadev-de-cert
  ldapPortName: ldaps
  oauth2ClientNamespaceSelector: {}
  gateway:
    parentRefs:
      - name: envoy
        namespace: networking
        sectionName: https
    backendTlsPolicy:
      validation:
        wellKnownCaCertificates: System
        hostname: idm.lucadev.de
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/description: Zentrale Nutzerverwaltung
      gethomepage.dev/group: Weitere
      gethomepage.dev/icon: mdi-account-lock
      gethomepage.dev/name: kanidm
