---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ./volsync.yaml
  - ./certificate.yaml
  - ./kanidm.yaml
  - ./ldap-service.yaml
  - ./groups/admins.yaml
  - ./groups/file-users.yaml
  - ./groups/home-baeckers.yaml
  - ./groups/home-maria.yaml
  - ./groups/media-guests.yaml
  - ./groups/media-users.yaml
  - ./groups/service-users.yaml
  - ./groups/vpn-users.yaml
  - ./clients/cloudflare.yaml
