---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: zigbee2mqtt
spec:
  kanidmRef:
    name: kanidm
    namespace: security
  displayname: "Zigbee2MQTT"
  origin: "https://z2m.lucadev.de/"
  redirectUrl:
    - "https://z2m.lucadev.de/oidc/callback"
  scopeMap:
    - group: admins
      scopes: [email, openid, profile]
  disableConsentPrompt: true
