---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kubeexposure-forwarder-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: kubeexposure-forwarder-secret
  data:
    - secretKey: auth-token
      remoteRef:
        key: 3f834e86-54b8-4f67-bf4f-b45b012e3d57
        property: local-cluster-auth-token
