---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: chhoto-url
spec:
  kanidmRef:
    name: kanidm
    namespace: security
  displayname: "Links"
  origin: "https://link.lucadev.de/"
  redirectUrl:
    - "https://link.lucadev.de/oidc/callback"
  scopeMap:
    - group: service_users
      scopes: [email, groups, openid, profile]
  disableConsentPrompt: true
