---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: filebrowser
spec:
  kanidmRef:
    name: kanidm
  displayname: "FileBrowser"
  origin: "https://files.lucadev.de/"
  redirectUrl:
    - "https://files.lucadev.de/oidc/callback"
    - "https://files.lucadev.de/api/auth/oidc/callback"
  scopeMap:
    - group: file_users
      scopes: [email, groups, openid, profile]
  preferShortUsername: true
  disableConsentPrompt: true
  allowInsecureClientDisablePkce: true
