---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: ersatztv
spec:
  kanidmRef:
    name: kanidm
  displayname: "ErsatzTV"
  origin: "https://tv.lucadev.de/"
  redirectUrl:
    - "https://tv.lucadev.de/callback"
  scopeMap:
    - group: admins
      scopes: [openid]
  disableConsentPrompt: true
