---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: alertmanager
spec:
  kanidmRef:
    name: kanidm
    namespace: security
  displayname: "Alertmanager"
  origin: "https://alertmanager.lucadev.de/"
  redirectUrl:
    - "https://alerts.lucadev.de/oidc/callback"
  scopeMap:
    - group: idm_all_persons
      scopes:
        - email
        - groups
        - openid
        - profile
  disableConsentPrompt: true
