---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bitwarden-cli
  namespace: secrets
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: bitwarden-cli
    template:
      data:
        BW_CLIENT_ID: "{{.bw_client_id}}"
        BW_CLIENT_SECRET: "{{.bw_client_secret}}"
        BW_PASSWORD: "{{.bw_password}}"
  data:
    - secretKey: bw_client_id
      remoteRef:
        key: external-secrets-bitwarden
        property: bw_client_id
    - secretKey: bw_client_secret
      remoteRef:
        key: external-secrets-bitwarden
        property: bw_client_secret
    - secretKey: bw_password
      remoteRef:
        key: external-secrets-bitwarden
        property: bw_password
